---
title: "Nature and DRT Report"
author: '[Spencer Castro](http://spencercastro.com)'
date: "11/18/2016"
output:
  pdf_document:
    toc: yes
  html_document:
    code_folding: hide
    fig_height: 4
    highlight: pygments
    theme: yeti
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.path='Figs/', fig.align='center',
                      warning=FALSE, message=FALSE, results='hide')
```

<div style="background-color:rgba(0, 0, 1,.04); text-align:center; vertical-align: middle; padding:40px 0;">
##The Attention Restoration Theory and Detection Response Task Results
</div>

<div style="background-color:rgba(0, 0, 1,.04); text-align:center; vertical-align: middle; padding:0px 0;">
The data below are first gathered in three datasets: <b>clean</b>, <b>clean.mean</b>, and <b>clean.rt</b>. the data.frame <b>clean</b> has a column for false alarms
</div>

```{r r intro_data,include=FALSE}
source("Load_Data.R")
combined.data <- CombineData()
clean.data <- CleanData(combined.data)

#Create Dataframes
clean <- clean.data %>%
  filter(isPractice == "no", pressCount == 1 | pressCount == 0) %>%
  group_by(subid,condition,r1g0) %>%
  dplyr::mutate(falsealarm = ifelse(pressCount == 1 & r1g0 == "r", 1,0)) %>%
  dplyr::mutate(miss = ifelse(pressCount == 0 & r1g0 == "g", 1,0)) %>%
  dplyr::mutate(totalerrors = miss + falsealarm)

clean.mean <- clean %>%
  group_by(subid,condition, r1g0) %>%
  dplyr::summarise(perc_error = mean(totalerrors)*100)

clean.rt <- clean %>%
  select(subid,condition,r1g0,rt,falsealarm) %>%
  filter(rt >= 150 & rt <= 2000)

```

## Participants Failing to respond correctly over 50%


```{r pressure, echo=FALSE}

```

